"""empty message

Revision ID: 733581554231
Revises: c06ec2096597
Create Date: 2025-01-27 19:04:53.402832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733581554231'
down_revision = 'c06ec2096597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people', sa.String(length=30), nullable=True))
        batch_op.drop_column('peoples')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peoples', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_column('people')

    # ### end Alembic commands ###
