"""empty message

Revision ID: c06ec2096597
Revises: 36d9ad5a8711
Create Date: 2025-01-27 19:01:37.678751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06ec2096597'
down_revision = '36d9ad5a8711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peoples', sa.String(length=30), nullable=True))
        batch_op.drop_column('people')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_column('peoples')

    # ### end Alembic commands ###
